services:
  backend:
    build:
      context: backend   
      target: builder
    ports:
        - "8000:8000"   
    secrets:
      - db-password
    depends_on:
      db:
        condition: service_healthy
  homebackend:
    build:
      context: homebackend
      target: builder
    ports:
        - "8001:8001"  
    secrets:
      - db-password
    depends_on:
      db:
        condition: service_healthy
  backend1:
    build:
      context: ./backend1
    ports:
      - "8003:8003"       
 # homebackend-copy:
  #  build:
   #   context: homebackend-copy
    #  target: builder
    #secrets:
    #  - db-password
    #depends_on:
    #  db:
    #    condition: service_healthy            
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - homebackend
      - backend1
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl   
      

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
